name: Hello World Example

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Say hello
      run: echo Hello, world!

    - name: Hello again
      run: docker run hello-world