name: Hello World Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    - name: Say hello
      run: echo Hello, world!

    - name: Hello again
      run: docker run hello-world