name: Hello World Example

on:
  workflow_dispatch:


jobs:
  local_hello:
    runs-on: self-hosted
    steps:
    - name: Say hello
      run: echo Hello, world!

  docker_hello:
    runs-on: self-hosted
    steps:
    - name: Hello again
      run: docker run hello-world

  